#!/bin/sh -l
# FILENAME: codecDriverSlurmScript

#LOAD ANY MODULES
#module load ffmpeg

# Change to the directory from which you originally submitted this job.
cd $SLURM_SUBMIT_DIR

# Runs a python script
python /home/alexa157/CodecTune/CDBTune/environment/driver.py
