#!/bin/sh -l
# FILENAME: trainingSlurmScript

#LOAD ANY MODULES
#module load ffmpeg

# Change to the directory from which you originally submitted this job.
cd $SLURM_SUBMIT_DIR

# Runs a python script
python /home/alexa157/CodecTune/CDBTune/environment/build/train.py --input /home/alexa157/CodecTune/CDBTune/globfile --width 1280 --height 720 --fps 30
